name: user_record
description: "A New Flutter User Record project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
