// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczoWg4_EN-iakRcHsptC8Xe-Bvtbyyog',
    appId: '1:881723513767:web:4788de801c2ad89e3f3482',
    messagingSenderId: '881723513767',
    projectId: 'userrecord-daf16',
    authDomain: 'userrecord-daf16.firebaseapp.com',
    storageBucket: 'userrecord-daf16.appspot.com',
    measurementId: 'G-XX8MQ1Q4G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh9rCSm6P_rwviFyjeVz6G7fe7pSGB52o',
    appId: '1:881723513767:android:b35320c0e91d5ada3f3482',
    messagingSenderId: '881723513767',
    projectId: 'userrecord-daf16',
    storageBucket: 'userrecord-daf16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_BeIxHDIIPVavyy6cqXy2V-_UFzzoqw',
    appId: '1:881723513767:ios:59a84daceb9044893f3482',
    messagingSenderId: '881723513767',
    projectId: 'userrecord-daf16',
    storageBucket: 'userrecord-daf16.appspot.com',
    iosBundleId: 'com.example.userRecord',
  );
}
